name: gh-pages deployment

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install nmrium and create toc
        run: |
          npm i nmrium-cli --global
          nmrium deleteJSONs
          nmrium createExercisesTOC
          nmrium deleteStructures
          nmrium appendLinks
          git status
          git remote -v
      - name: push to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
